### ISSUE TITLE
Logpoint expressions aren't URL encoded

### ISSUE THREAD

**Issue by nikmd23** [lostintangent/azjs#29]
I think this issue was intended to be fixed in `0.2.1`, but I'm still seeing the old behavior. For example:

```
azjs logpoint add -f server/routes/create.js -l 33 -e keyword[1]
```

does not work. But if I URL encode the -e expression like this

```
azjs logpoint add -f server/routes/create.js -l 33 -e keyword%5B1%5D
```

it does work.

**Comment by lostintangent** [comment]
This has been fixed. Thanks for reporting this!

**Comment by nikmd23** [comment]
Has the fixed version been released?

**Comment by lostintangent** [comment]
It is now! Try out the latest bits on NPM and let me know if you run into any issues.
